config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'pages/home'
  root to: 'teams#index'
  resources :teams, only: [:index, :show, :new, :create] do
    resources :signings, only: [:new, :create]
  end
  resources :signings, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/player.rb
class Player < ApplicationRecord
  has_many :signings
  has_many :teams
  has_one_attached :photo
  validates :name, presence: true
  # validates :position, presence: true


end

app/models/signing.rb
class Signing < ApplicationRecord
  belongs_to :team
  belongs_to :player
  validates :player, presence: true, uniqueness: { scope: :team }
  POSITIONS = ['Goalkeeper', 'Right Back', 'Left Back', 'Center Back', 'Sweeper', 'Left Wing', 'Right Wing', 'Defensive Midfield', 'Centre Midfield', 'Attacking Midfield', 'Left Midfield', 'Right Midfield', 'Stiker' ]
  validates :position, inclusion: { in: POSITIONS }

  # def player_name
  #   player.name if player
  # end

  # def player_name=(name)
  #   self.player = Player.find_by_name(name) if name.present?
  # end
end

app/models/team.rb
class Team < ApplicationRecord
  has_many :signings, dependent: :destroy
  has_many :players, through: :signings
  has_one_attached :photo
  validates :name, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/signings_controller.rb
class SigningsController < ApplicationController
  def new
    if params[:query].present?
      @players = Player.where("name ILIKE ?", "%#{params[:query]}%").first(8)
    else
      @players = Player.first(8)
    end
    # @players = Player.where(name: params[:name]) if params[:name].present?

    @signing = Signing.new
    @team = Team.find(params[:team_id])
    # @players = Player.where.not(id: @team.players).order(name: :asc)
    @positions = ['Goalkeeper', 'Right Back', 'Left Back', 'Center Back', 'Sweeper', 'Left Wing', 'Right Wing', 'Defensive Midfield', 'Centre Midfield', 'Attacking Midfield', 'Left Midfield', 'Right Midfield', 'Stiker' ]
  end

  def create
    @signing = Signing.new(signing_params)
    @team = Team.find(params[:team_id])
    @signing.team = @team
    if @signing.player.nil?
      redirect_to new_team_signing_path(@team), flash: {notice: 'Please select a player'}
      return false
    else
      @signing.player.position = @signing.position
    end
    if @signing.save
      redirect_to team_path(@team)
    else
      if params[:query].present?
        @players = Player.where("title ILIKE ?", "%#{params[:query]}%").first(8)
      else
        @players = Player.first(8)
      end
      @positions = ['Goalkeeper', 'Right Back', 'Left Back', 'Center Back', 'Sweeper', 'Left Wing', 'Right Wing', 'Defensive Midfield', 'Centre Midfield', 'Attacking Midfield', 'Left Midfield', 'Right Midfield', 'Stiker' ]
      # @players = Player.where.not(id: @team.players).order(name: :asc)
      # @players = Player.find(:all, conditions: ['name LIKE ?', "%#{params[:search]}%"])
      render :new
    end
  end

  def destroy
    @signing = Signing.find(params[:id])
    @signing.destroy
    redirect_to team_path(@signing.team)
  end

  private

  def signing_params
    params.require(:signing).permit(:position, :player_id)
  end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  def index
    @teams = Team.all
  end

  def show
    @team = Team.find(params[:id])
    @signings = @team.signings
    @players = Player.all
  end

  def new
    @team = Team.new
  end

  def create
    @team = Team.new(team_params)
    if @team.save
      redirect_to team_path(@team)
    else
      render :new
    end
  end

  private

  def team_params
    params.require(:team).permit(:name, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Fantasy Dream Team</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
    <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
    <link rel="manifest" href="/site.webmanifest">
    <%= favicon_link_tag asset_path('favicon.ico') %>
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>
  <body>
    <div class="notice">
      <%= flash[:notice] %>
    </div>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/signings/new.html.erb
<div class="container p-3">
  <nav class="">
    <%= link_to teams_path, class: 'nav-a' do %>
      <p><i class="fas fa-home"></i></p>
    <% end %>
    <%= link_to team_path(@team), class: 'nav-a' do %>
      <p><i class="fas fa-user-friends"></i></p>
    <% end %>
    <%# <a class="navbar-brand" href="#">Navbar</a> %>
  </nav>
  <h1>Add a player</h1>
  <%= form_tag new_team_signing_path, method: :get, class: 'search-form p-4 mt-3' do %>
    <%= text_field_tag :query,
    params[:query],
    class: "form-control search-bar",
    placeholder: "Find a player"
  %>
    <%= submit_tag "Search", class: "search-btn" %>
  <% end %>
  <div class=" form container card p-4 bg-dark mt-2">
    <%# <h1>Spawn a Monster</h1> %>
    <%= simple_form_for [@team, @signing] do |f| %>
      <%= f.association :player, collection: @players, as: :radio_buttons, checked: @players[0], collection_wrapper_tag: 'div',
        collection_wrapper_class: 'category-wrapper',
        item_wrapper_class: 'category-item',
        input_html: {class: 'category-selector'}, class: 'new-place-input', label: "Player (Search to see more players)" %>
      <%= f.input :position, collection: @positions, as: :radio_buttons, collection_wrapper_tag: 'div',
        collection_wrapper_class: 'category-wrapper',
        item_wrapper_class: 'category-item',
        input_html: {class: 'category-selector'}, class: 'new-place-input', checked: 'Goalkeeper' %>
      <%# <%= f.input :image_url %>
      <%= f.submit 'Add', class: 'add-btn' %>
    <% end %>
  </div>
</div>